<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="script" nsURI="http://www.meta_excel.org/script" nsPrefix="script">
  <eClassifiers xsi:type="ecore:EClass" name="Script">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScriptElement" lowerBound="2"
        upperBound="-1" eType="#//ScriptElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="OperationElement" upperBound="-1"
        eType="#//OperationTypeElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScriptElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Input" eSuperTypes="#//ScriptElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output" eSuperTypes="#//ScriptElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" eSuperTypes="#//ScriptElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operand" upperBound="-1"
        eType="#//ScriptElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opType" lowerBound="1"
        eType="#//OperationTypeElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constante" eSuperTypes="#//ScriptElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationTypeElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationType" eSuperTypes="#//OperationTypeElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nbOperands" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
