<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algorithm" nsURI="http://www.meta_excel.org/algorithm" nsPrefix="algorithm">
  <eClassifiers xsi:type="ecore:EClass" name="Algorithm">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" lowerBound="1"
        upperBound="-1" eType="#//Input" containment="true" eOpposite="#//Input/algorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Output" containment="true" eOpposite="#//Output/algorithm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Input">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" upperBound="-1"
        eType="ecore:EClass http://www.meta_excel.org/table/table.ecore#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" lowerBound="1"
        eType="#//Algorithm" eOpposite="#//Algorithm/inputs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" upperBound="-1"
        eType="ecore:EClass http://www.meta_excel.org/script/script.ecore#//Input"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Output">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.meta_excel.org/table/table.ecore#//Column"
        eOpposite="http://www.meta_excel.org/table/table.ecore#//Column/derivateFrom"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm" lowerBound="1"
        eType="#//Algorithm" eOpposite="#//Algorithm/output"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="script" lowerBound="1"
        upperBound="-1" eType="ecore:EClass http://www.meta_excel.org/script/script.ecore#//Output"/>
  </eClassifiers>
</ecore:EPackage>
