<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Librairie">
  <eClassifiers xsi:type="ecore:EClass" name="Librairie">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Algo" upperBound="-1" eType="ecore:EClass algorithm.ecore#//Algorithm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donnees" upperBound="-1"
        eType="#//DonneesCol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="donneesext" upperBound="-1"
        eType="#//DonneesExt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Val">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donnees" lowerBound="1"
        eType="#//DonneesCol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Column" eType="ecore:EClass table.ecore#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IdVal">
    <eStructuralFeatures xsi:type="ecore:EReference" name="donnees" lowerBound="1"
        eType="#//DonneesCol" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="IdColumn" eType="ecore:EClass table.ecore#//IdentColumn"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonneesCol">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DonneesExt"/>
</ecore:EPackage>
